[package]
version = "0.8.2"
name = "lockbook-cli"
edition = "2021"

[[bin]]
name = "lockbook"
path = "src/main.rs"

[dependencies]
lb = { path = "../../libs/lb/lb-rs", package = "lb-rs" }
cli-rs = "0.1.12"
is-terminal = "0.4.7"
hotwatch = "0.5.0"
