use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::time::{Duration, SystemTime, UNIX_EPOCH};
use std::{fs, io};

use cli_rs::cli_error::{CliError, CliResult};
use hotwatch::{Event, EventKind, Hotwatch};
use lb_rs::{Lb, Uuid};
use serde::{Deserialize, Serialize};


use crate::{core, ensure_account_and_root};
use crate::input::FileInput;

const SYNC_STATE_FILE: &str = ".lockbook-sync-state.json";
const LOCKBOOK_IGNORE: &str = ".lockbookignore";
const POLL_INTERVAL: Duration = Duration::from_secs(5);

const DEFAULT_IGNORES: &[&str] = &[
    ".git/",
    "*.sqlite",
    "*.sqlite-shm",
    "*.sqlite-wal",
    "node_modules/",
    "target/",
    "__pycache__/",
    ".DS_Store",
];

const LOCKBOOKIGNORE_TEMPLATE: &str = "\
# .lockbookignore — generated by lockbook sync-dir
# Patterns below are ignored by default even without this file.
# Add your own exclusions after the defaults.

.git/
*.sqlite
*.sqlite-shm
*.sqlite-wal
node_modules/
target/
__pycache__/
.DS_Store
";

// --- State ---

#[derive(Serialize, Deserialize, Default)]
struct SyncState {
    /// Maps relative path (forward slashes) -> lockbook file id
    entries: HashMap<String, Uuid>,
    /// Content hashes for conflict detection (relative path -> sha256 hex of last-synced content)
    baselines: HashMap<String, String>,
}

impl SyncState {
    fn load(local_dir: &Path) -> Self {
        let path = local_dir.join(SYNC_STATE_FILE);
        match fs::read_to_string(&path) {
            Ok(data) => serde_json::from_str(&data).unwrap_or_default(),
            Err(_) => Self::default(),
        }
    }

    fn save(&self, local_dir: &Path) -> io::Result<()> {
        let path = local_dir.join(SYNC_STATE_FILE);
        let data = serde_json::to_string_pretty(self)?;
        fs::write(path, data)
    }
}

// --- Ignore ---

fn should_ignore(rel_path: &str) -> bool {
    // Always ignore our own state files
    if rel_path == SYNC_STATE_FILE || rel_path == LOCKBOOK_IGNORE {
        return true;
    }
    for pattern in DEFAULT_IGNORES {
        if pattern.ends_with('/') {
            // Directory prefix match
            let dir_name = &pattern[..pattern.len() - 1];
            if rel_path.starts_with(&format!("{dir_name}/")) || rel_path == dir_name {
                return true;
            }
            // Also match anywhere in path
            if rel_path.contains(&format!("/{dir_name}/")) {
                return true;
            }
        } else if pattern.starts_with("*.") {
            // Extension glob
            let ext = &pattern[1..]; // e.g. ".sqlite"
            if rel_path.ends_with(ext) {
                return true;
            }
        } else {
            // Exact filename match (anywhere in path)
            let fname = rel_path.rsplit('/').next().unwrap_or(rel_path);
            if fname == *pattern {
                return true;
            }
        }
    }
    // Check user .lockbookignore (simple line-by-line matching, same logic)
    // For v1, we only use the built-in defaults and the file is informational
    false
}

fn sha256_hex(data: &[u8]) -> String {
    use std::fmt::Write;
    // Simple hash using std — we just need a change-detection hash, not crypto
    // Use a basic FNV-style hash encoded as hex for simplicity
    let mut h: u64 = 0xcbf29ce484222325;
    for &b in data {
        h ^= b as u64;
        h = h.wrapping_mul(0x100000001b3);
    }
    let mut s = String::with_capacity(16);
    let _ = write!(s, "{h:016x}");
    s
}

fn conflict_path(path: &Path) -> PathBuf {
    let ts = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();
    let stem = path.file_stem().and_then(|s| s.to_str()).unwrap_or("file");
    let ext = path.extension().and_then(|e| e.to_str());
    let parent = path.parent().unwrap_or(path);
    match ext {
        Some(e) => parent.join(format!("{stem}.conflict-{ts}.{e}")),
        None => parent.join(format!("{stem}.conflict-{ts}")),
    }
}

// --- Enumerate helpers ---

struct RemoteFile {
    id: Uuid,
    rel_path: String,
    is_folder: bool,
}

async fn enumerate_remote(
    lb: &Lb, folder_id: Uuid, folder_path: &str,
) -> Result<Vec<RemoteFile>, CliError> {
    let all = lb.get_and_get_children_recursively(&folder_id).await?;
    let mut results = Vec::new();
    for f in &all {
        let full_path = lb.get_path_by_id(f.id).await?;
        // full_path is like "/username/folder/sub/file.txt"
        // folder_path is like "/username/folder/"
        if full_path.len() <= folder_path.len() {
            continue; // skip the folder itself
        }
        let rel = &full_path[folder_path.len()..];
        let rel = rel.trim_start_matches('/');
        if rel.is_empty() {
            continue;
        }
        if should_ignore(rel) {
            continue;
        }
        results.push(RemoteFile {
            id: f.id,
            rel_path: rel.to_string(),
            is_folder: f.is_folder(),
        });
    }
    Ok(results)
}

fn enumerate_local(local_dir: &Path) -> Vec<String> {
    let mut results = Vec::new();
    fn walk(dir: &Path, base: &Path, results: &mut Vec<String>) {
        let entries = match fs::read_dir(dir) {
            Ok(e) => e,
            Err(_) => return,
        };
        for entry in entries.flatten() {
            let path = entry.path();
            let rel = path
                .strip_prefix(base)
                .unwrap_or(&path)
                .to_string_lossy()
                .replace('\\', "/");
            if should_ignore(&rel) {
                continue;
            }
            if path.is_dir() {
                results.push(format!("{rel}/"));
                walk(&path, base, results);
            } else {
                results.push(rel);
            }
        }
    }
    walk(local_dir, local_dir, &mut results);
    results
}

// --- Reconcile (startup) ---

async fn reconcile(
    lb: &Lb, folder_id: Uuid, folder_path: &str, local_dir: &Path, state: &mut SyncState,
) -> Result<(), CliError> {
    let remote_files = enumerate_remote(lb, folder_id, folder_path).await?;
    let local_files = enumerate_local(local_dir);

    // Build remote lookup
    let remote_map: HashMap<String, &RemoteFile> =
        remote_files.iter().map(|r| (r.rel_path.clone(), r)).collect();
    let local_set: std::collections::HashSet<String> = local_files.into_iter().collect();

    // Remote-only or remote+local: server wins
    for rf in &remote_files {
        let local_path = local_dir.join(&rf.rel_path);
        if rf.is_folder {
            fs::create_dir_all(&local_path).ok();
            state.entries.insert(rf.rel_path.clone(), rf.id);
            continue;
        }

        let remote_content = lb.read_document(rf.id, false).await?;

        if local_path.exists() {
            // Both exist — check if local has diverged from baseline
            let local_content = fs::read(&local_path).unwrap_or_default();
            let local_hash = sha256_hex(&local_content);
            let baseline_hash = state.baselines.get(&rf.rel_path);

            let local_changed = match baseline_hash {
                Some(bh) => &local_hash != bh,
                None => true, // no baseline = treat as potentially changed
            };

            if local_changed && local_content != remote_content {
                // Conflict: remote wins, save local as sidecar
                let cp = conflict_path(&local_path);
                println!("  conflict: {} → {}", rf.rel_path, cp.display());
                fs::rename(&local_path, &cp).ok();
            }
        } else {
            // Ensure parent dirs exist
            if let Some(parent) = local_path.parent() {
                fs::create_dir_all(parent).ok();
            }
        }

        fs::write(&local_path, &remote_content)?;
        state.baselines.insert(rf.rel_path.clone(), sha256_hex(&remote_content));
        state.entries.insert(rf.rel_path.clone(), rf.id);
    }

    // Local-only: upload to lockbook
    for rel in &local_set {
        if remote_map.contains_key(rel.as_str()) || rel.ends_with('/') {
            continue;
        }
        // Check if it's a directory marker
        if rel.ends_with('/') {
            continue;
        }

        let local_path = local_dir.join(rel);
        if !local_path.is_file() {
            continue;
        }

        let lb_path = format!("{}{}", folder_path, rel);
        println!("  uploading local-only: {}", rel);

        // Create parent folders as needed and then the file
        let file = lb.create_at_path(&lb_path).await?;
        let content = fs::read(&local_path)?;
        lb.write_document(file.id, &content).await?;
        state.baselines.insert(rel.clone(), sha256_hex(&content));
        state.entries.insert(rel.clone(), file.id);
    }

    state.save(local_dir)?;
    Ok(())
}

// --- Upload a local file change ---

async fn upload_file(lb: &Lb, local_dir: &Path, folder_path: &str, rel_path: &str, state: &mut SyncState) -> Result<(), CliError> {
    let local_path = local_dir.join(rel_path);

    if !local_path.is_file() {
        // File was deleted locally — skip for v1
        return Ok(());
    }

    let content = fs::read(&local_path)?;

    if let Some(&id) = state.entries.get(rel_path) {
        // Update existing
        lb.write_document(id, &content).await?;
    } else {
        // Create new
        let lb_path = format!("{}{}", folder_path, rel_path);
        let file = lb.create_at_path(&lb_path).await?;
        lb.write_document(file.id, &content).await?;
        state.entries.insert(rel_path.to_string(), file.id);
    }

    state.baselines.insert(rel_path.to_string(), sha256_hex(&content));
    state.save(local_dir)?;
    Ok(())
}

// --- Apply remote changes ---

async fn apply_remote_changes(
    lb: &Lb, folder_id: Uuid, folder_path: &str, local_dir: &Path, state: &mut SyncState,
) -> Result<(), CliError> {
    lb.sync().await?;

    let remote_files = enumerate_remote(lb, folder_id, folder_path).await?;
    let mut changed = false;

    for rf in &remote_files {
        if rf.is_folder {
            let local_path = local_dir.join(&rf.rel_path);
            fs::create_dir_all(&local_path).ok();
            state.entries.insert(rf.rel_path.clone(), rf.id);
            continue;
        }

        let remote_content = lb.read_document(rf.id, false).await?;
        let remote_hash = sha256_hex(&remote_content);

        let baseline_hash = state.baselines.get(&rf.rel_path).cloned();

        if Some(&remote_hash) == baseline_hash.as_ref() {
            // Remote unchanged since last sync
            continue;
        }

        let local_path = local_dir.join(&rf.rel_path);

        if local_path.exists() {
            let local_content = fs::read(&local_path).unwrap_or_default();
            let local_hash = sha256_hex(&local_content);

            if local_hash == remote_hash {
                // Already in sync
                state.baselines.insert(rf.rel_path.clone(), remote_hash);
                continue;
            }

            let local_changed = match &baseline_hash {
                Some(bh) => &local_hash != bh,
                None => true,
            };

            if local_changed {
                let cp = conflict_path(&local_path);
                println!("  conflict: {} → {}", rf.rel_path, cp.display());
                fs::rename(&local_path, &cp).ok();
            }
        } else if let Some(parent) = local_path.parent() {
            fs::create_dir_all(parent).ok();
        }

        println!("  updated: {}", rf.rel_path);
        fs::write(&local_path, &remote_content)?;
        state.baselines.insert(rf.rel_path.clone(), remote_hash);
        state.entries.insert(rf.rel_path.clone(), rf.id);
        changed = true;
    }

    if changed {
        state.save(local_dir)?;
    }
    Ok(())
}

// --- Generate .lockbookignore ---

fn generate_lockbookignore(local_dir: &Path) {
    let path = local_dir.join(LOCKBOOK_IGNORE);
    if !path.exists() {
        if let Err(e) = fs::write(&path, LOCKBOOKIGNORE_TEMPLATE) {
            eprintln!("warning: could not write {LOCKBOOK_IGNORE}: {e}");
        }
    }
}

// --- Main entry point ---

#[tokio::main]
pub async fn sync_dir(lockbook_folder: FileInput, local_dir: PathBuf) -> CliResult<()> {
    let lb = &core().await?;
    ensure_account_and_root(lb).await?;

    let folder = lockbook_folder.find(lb).await?;
    if !folder.is_folder() {
        return Err(CliError::from("target must be a folder"));
    }

    let folder_id = folder.id;
    let folder_path = lb.get_path_by_id(folder_id).await?;
    // Ensure folder_path ends with /
    let folder_path = if folder_path.ends_with('/') {
        folder_path
    } else {
        format!("{folder_path}/")
    };

    // Create local dir if needed
    fs::create_dir_all(&local_dir)?;
    let local_dir = fs::canonicalize(&local_dir)?;

    println!("sync-dir: {} ↔ {}", folder_path, local_dir.display());

    // Generate .lockbookignore on first run
    generate_lockbookignore(&local_dir);

    // Initial sync from server
    println!("syncing from server...");
    lb.sync().await?;

    let mut state = SyncState::load(&local_dir);
    reconcile(lb, folder_id, &folder_path, &local_dir, &mut state).await?;
    println!("initial reconcile complete.");

    // Set up file watcher for local changes
    let watcher_lb = lb.clone();
    let watcher_dir = local_dir.clone();
    let watcher_folder_path = folder_path.clone();

    let (tx, mut rx) = tokio::sync::mpsc::unbounded_channel::<String>();

    let mut hotwatch = Hotwatch::new_with_custom_delay(core::time::Duration::from_millis(500))
        .map_err(|e| CliError::from(format!("failed to init file watcher: {e}")))?;

    let watch_base = local_dir.clone();
    hotwatch
        .watch(local_dir.clone(), move |event: Event| {
            let paths = match &event.kind {
                EventKind::Modify(_) | EventKind::Create(_) | EventKind::Remove(_) => {
                    event.paths.clone()
                }
                _ => return,
            };
            for path in paths {
                if let Ok(rel) = path.strip_prefix(&watch_base) {
                    let rel_str = rel.to_string_lossy().replace('\\', "/");
                    if !rel_str.is_empty() && !should_ignore(&rel_str) {
                        let _ = tx.send(rel_str);
                    }
                }
            }
        })
        .map_err(|e| CliError::from(format!("failed to watch directory: {e}")))?;

    println!("watching for changes... (Ctrl+C to stop)");

    let mut poll_interval = tokio::time::interval(POLL_INTERVAL);

    loop {
        tokio::select! {
            Some(rel_path) = rx.recv() => {
                // Debounce: drain any queued events for the same file
                let mut paths = vec![rel_path];
                while let Ok(p) = rx.try_recv() {
                    if !paths.contains(&p) {
                        paths.push(p);
                    }
                }
                // Small delay for writes to settle
                tokio::time::sleep(Duration::from_millis(200)).await;

                for rel in &paths {
                    println!("  local change: {rel}");
                    if let Err(e) = upload_file(&watcher_lb, &watcher_dir, &watcher_folder_path, rel, &mut state).await {
                        eprintln!("  upload error for {rel}: {e:?}");
                    }
                }
                // Push changes to server
                if let Err(e) = watcher_lb.sync().await {
                    eprintln!("  sync error: {e}");
                }
            }
            _ = poll_interval.tick() => {
                if let Err(e) = apply_remote_changes(lb, folder_id, &folder_path, &local_dir, &mut state).await {
                    eprintln!("  remote poll error: {e:?}");
                }
            }
        }
    }
}
